### PR TITLE
Small fixes to make go-mruby compatible with 1.13 and 1.14 module environments

### PR DESCRIPTION
**Pull request by erikh**
A number of things in here, small fixes to the build. No logic changes and
everything should be compatible unless you depend on the headers or source in
the vendor/ directory. I had to move that.

I'll be addressing the oustanding patches in this repo once I get this in.

cc @mitchellh

Signed-off-by: Erik Hollensbe <github@hollensbe.org>

### CODE REVIEW

**Comment by erikh** [comment]
I hope it's ok, but I'm going to bump the minimum supported to 1.13.

**Comment by erikh** [comment]
I don't want to rush the merge on this but I also kind of do. I'll prepare the 2.0 patches others have supplied against this branch, once that's done and I'm satisfied with the work I'll probably end up merging this. Please feel free to block me in the meantime, and we can always revert if it anything in here is an issue.

**Comment by erikh** [comment]
Well that's actually the issue. I could massage it to make it look like a
gopath but anything that touches modules around it wants it to behave like
one with a `vendor/modules.txt`, etc., which I ran into some trouble with
regarding golint and staticcheck.

But since I stepped around that with `GO111MODULE=off`, basically it's
avoiding potential future issues at this point.

I could massage it further I suppose if you feel it's an issue worth
tackling, I just felt it easier to set the whole thing aside if we want to
use vendor in a golang-compatible way for ourselves later (unlikely I
think, but potentially).

**Comment by mitchellh** [comment]
It doesn't bother me that much, this is fine.

**Comment by erikh** [comment]
Thanks!

**Pull request merged**
