### PR TITLE
Describe where to put libmruby.a

### PR DESCRIPTION
**Pull request by kyab**
related to #2

### CODE REVIEW

**Comment by suzukaze** [comment]
@mitchellh 
This patch is nice.
When I executed go build sample go file, I found no such file or directory: 'libmruby.a' error.

**Comment by breml** [comment]
+1 for this very helpful hint.
@kyab thank you.

**Comment by erikh** [comment]
Thanks to #28 this is no longer necessary! Latest master has the change.

I'm going to close this. Let me know if it shouldn't be.

**Comment by kyab** [comment]
Thanks to #28 !

**Pull request closed without merging**
